ALTER TABLE "Listing" ADD COLUMN "variant" TEXT;
ALTER TABLE "Listing" ADD COLUMN "transmission" TEXT;
ALTER TABLE "Listing" ADD COLUMN "fuelType" TEXT;
ALTER TABLE "Listing" ADD COLUMN "bodyType" TEXT;
ALTER TABLE "Listing" ADD COLUMN "region" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketValuationStatus" TEXT NOT NULL DEFAULT 'NOT_STARTED';
ALTER TABLE "Listing" ADD COLUMN "marketValuationError" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketValueCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketComparableCount" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "marketLowestComparableCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketHighestComparableCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketAucklandMedianCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketDifferenceCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketDifferencePercent" REAL;
ALTER TABLE "Listing" ADD COLUMN "marketRelation" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketVerdict" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketConfidence" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketReason" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketTargetSellCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketMaxBuyCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketExpectedSpreadCents" INTEGER;
ALTER TABLE "Listing" ADD COLUMN "marketSourcesAttempted" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "marketSourcesSuccessful" INTEGER NOT NULL DEFAULT 0;
ALTER TABLE "Listing" ADD COLUMN "marketSourceBreakdownJson" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketComparablesJson" TEXT;
ALTER TABLE "Listing" ADD COLUMN "marketValuedAt" DATETIME;
ALTER TABLE "Listing" ADD COLUMN "marketValuationRunId" TEXT;

CREATE INDEX "Listing_marketValuationStatus_idx" ON "Listing"("marketValuationStatus");
CREATE INDEX "Listing_marketVerdict_idx" ON "Listing"("marketVerdict");
CREATE INDEX "Listing_marketValuedAt_idx" ON "Listing"("marketValuedAt");
